services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/data:/app/data
      - data:/var/lib/grafana
    networks:
      lan:
        ipv4_address: 172.20.0.13

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      lan:
        ipv4_address: 172.20.0.14

networks:
  lan:
    external: true

volumes:
  data: